server:
  port: 8888
spring:
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT prop_key, value FROM properties WHERE application=? AND profile=? AND label=?
  datasource:
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://db/cloud
  application:
    name: config-server
  profiles:
    active: jdbc
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    drop-first: true
    change-log: classpath:db/changelog/accumulative-changelog.yml
